# Generated by Django 4.1.3 on 2022-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[("id", models.IntegerField(primary_key=True, serialize=False)),],
            options={"db_table": "cart", "managed": False,},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "cart_item", "managed": False,},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "category", "managed": False,},
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "shipped_date",
                    models.CharField(blank=True, max_length=135, null=True),
                ),
                (
                    "created_date",
                    models.CharField(blank=True, max_length=135, null=True),
                ),
            ],
            options={"db_table": "orders", "managed": False,},
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "package", "managed": False,},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("total", models.FloatField(blank=True, null=True)),
                (
                    "payment_time",
                    models.CharField(blank=True, max_length=135, null=True),
                ),
            ],
            options={"db_table": "payment", "managed": False,},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("cost", models.FloatField(blank=True, null=True)),
                ("unit", models.IntegerField(blank=True, null=True)),
                ("weight", models.CharField(blank=True, max_length=45, null=True)),
                ("origin", models.CharField(blank=True, max_length=135, null=True)),
                (
                    "expirationdate",
                    models.CharField(
                        blank=True,
                        db_column="expirationDate",
                        max_length=135,
                        null=True,
                    ),
                ),
                ("keyword", models.CharField(blank=True, max_length=135, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "product", "managed": False,},
        ),
        migrations.CreateModel(
            name="RAddress",
            fields=[
                (
                    "address",
                    models.CharField(max_length=135, primary_key=True, serialize=False),
                ),
                ("latitude", models.CharField(blank=True, max_length=45, null=True)),
                ("longtitude", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "r_address", "managed": False,},
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("method", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "recipe", "managed": False,},
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("weight", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "recipe_ingredient", "managed": False,},
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("address", models.CharField(blank=True, max_length=135, null=True)),
                ("keyword", models.CharField(blank=True, max_length=135, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"db_table": "restaurant", "managed": False,},
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={"db_table": "status", "managed": False,},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=45, null=True)),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("email", models.CharField(blank=True, max_length=90, null=True)),
                ("address", models.CharField(blank=True, max_length=135, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=135, null=True),
                ),
            ],
            options={"db_table": "user", "managed": False,},
        ),
    ]
